### ISSUE TITLE
unmanaged exception if proxy started when is already running.

### ISSUE THREAD

**Issue by Barry4679** [henkelis/sonospy#41]
I don't know if this is the same as issue: https://github.com/henkelis/sonospy/issues/2

If the proxy is running, and attempt to start it again in error, I get an unmatched exception:

Traceback (most recent call last):
  File "./gettags", line 1728, in <module>
    status = main()
  File "./gettags", line 1717, in main
    generate_subset(options, database, newdatabase, options.where)
  File "./gettags", line 1193, in generate_subset
    c.execute(statement)
Warning: You can only execute one statement at a time.

**Comment by ianmacd** [comment]
Huh? Why would the proxy run <tt>gettags</tt>?

Was this part of some start-up script?

**Comment by Barry4679** [comment]
Well spotted Ian. Thanks.

Add to the ticket that the exception is so unmanaged that it doesn't create a log in the errors directory:

The exception info in the cmd windows is:
 Args:                                                                 Album Year
 option.proxyonly: True
     WMP proxy: Sonospy=Rock,Rock.db
     WMP proxy: Sonospy=Jazz,Jazz.db
     WMP proxy: Sonospy=rock3,rock3.db
 Proxy. Name: Rock                                                        Address
 Traceback (most recent call last):
   File "pycpoint.py", line 5686, in <module>
     main()
   File "pycpoint.py", line 5673, in main
     web = ControlPointWeb()
   File "pycpoint.py", line 594, in **init**
     proxy.start()
   File "D:\Documents and Settings\BMOSS\My Documents\Sonos Project\henkelis-son
 spy-7b71de7\sonospy\proxy.py", line 166, in start
     self._load()
   File "D:\Documents and Settings\BMOSS\My Documents\Sonos Project\henkelis-son
 spy-7b71de7\sonospy\proxy.py", line 159, in _load
     self._add_root_device()
   File "D:\Documents and Settings\BMOSS\My Documents\Sonos Project\henkelis-son
 spy-7b71de7\sonospy\proxy.py", line 128, in _add_root_device
     force_listen_url=listen_url)
   File "D:\Documents and Settings\BMOSS\My Documents\Sonos Project\henkelis-son
 spy-7b71de7\sonospy\brisa\upnp\device\device.py", line 81, in __init__
     self._create_webserver(force_listen_url)
   File "D:\Documents and Settings\BMOSS\My Documents\Sonos Project\henkelis-son
 spy-7b71de7\sonospy\brisa\upnp\device\device.py", line 100, in _create_webserve
     self.webserver = webserver.WebServer(host=p.hostname, port=p.port)
   File "D:\Documents and Settings\BMOSS\My Documents\Sonos Project\henkelis-son
 spy-7b71de7\sonospy\brisa\core\webserver.py", line 1482, in __init__
     self.set_bind_address(self.host, self.port)
   File "D:\Documents and Settings\BMOSS\My Documents\Sonos Project\henkelis-son
 spy-7b71de7\sonospy\brisa\core\webserver.py", line 1538, in set_bind_address
     raise ValueError('URL cannot be used by the webserver.')
 ValueError: URL cannot be used by the webserver.
 D:\Documents and Settings\BMOSS\My Documents\Sonos Project\henkelis-sonospy-7b7
 de7\sonospy>

**Comment by ianmacd** [comment]
How are you starting it? What command are you using? If a launcher, what command is it using? <tt>sonospy_p.cmd</tt>?

That file is broken in similar ways to <tt>sonospy_proxy</tt>, one symptom of which is documented in #2.

**Comment by henkelis** [comment]
For clarity, exceptions from the proxy are not currently written to logs.

The second instance of the proxy is trying to bind to the address that the first is already using, so it fails.
