### ISSUE TITLE
Scan problem of a newbie

### ISSUE THREAD

**Issue by germangooner** [henkelis/sonospy#71]
Hello everyone,

first a big thanks for all the work to get around the 65k limit...and a special thanks to Mark Henkelis; thank you Mark; great work!

Being not familiar with neither python nor linux, it took me a lot of tries to get sonospy to work on my system. (Sonos ZP90, Windows XP SP3 , Qnap NAS TS-219; Ipad 1)

I finally got it running on the web-browser. I use Mediamonkey which is running on my windows-machine. Mediamonkey gets the files from my NAS.

What doesn't work is: I'd like to use the database on my Ipad Controller. I did a testscan on my windows-machine with some files from my NAS and it worked out fine. I deceided to do a complete scan (about 115k files) and had errors.Most of the folders on my NAS work, some not and I don't know the reason why and what to do. 

Here is the the Test.log:

Error creating database: C:\sonospy-unstable\sonospy\Sonos.db : unable to open database file
Database: C:\sonospy-unstable\sonospy\Sonos.db
Scanning: \192.168.2.38\Sonos\Sonos Music\12345\21 Guns
Scannumber: 1
New file found: 01 - Knee Deep.flac, \192.168.2.38\Sonos\Sonos Music\12345\21 Guns\Salute (1992)
New file found: 02 - These Eyes.flac, \192.168.2.38\Sonos\Sonos Music\12345\21 Guns\Salute (1992)
New file found: 03 - Walking.flac, \192.168.2.38\Sonos\Sonos Music\12345\21 Guns\Salute (1992)
New file found: 04 - Marching In Time.flac, \192.168.2.38\Sonos\Sonos Music\12345\21 Guns\Salute (1992)
New file found: 05 - The Rain.flac, \192.168.2.38\Sonos\Sonos Music\12345\21 Guns\Salute (1992)
New file found: 06 - Little Sister.flac, \192.168.2.38\Sonos\Sonos Music\12345\21 Guns\Salute (1992)
New file found: 07 - Pays Off Big.flac, \192.168.2.38\Sonos\Sonos Music\12345\21 Guns\Salute (1992)
New file found: 08 - Just A Wish.flac, \192.168.2.38\Sonos\Sonos Music\12345\21 Guns\Salute (1992)
New file found: 09 - Battered And Bruised.flac, \192.168.2.38\Sonos\Sonos Music\12345\21 Guns\Salute (1992)
New file found: 10 - Jungleland.flac, \192.168.2.38\Sonos\Sonos Music\12345\21 Guns\Salute (1992)
New file found: 11 - Tell Me.flac, \192.168.2.38\Sonos\Sonos Music\12345\21 Guns\Salute (1992)
New file found: 12 - No Way Out.flac, \192.168.2.38\Sonos\Sonos Music\12345\21 Guns\Salute (1992)
Error processing track changes against workvirtuals: no such table: workvirtuals
Error processing workvirtual track deletions: no such table: workvirtuals
Error processing track changes against playlists: no such table: playlists
Error processing playlist track deletions: no such table: playlists
Error deleting playlists_update entries: no such table: playlists_update
Error creating database: C:\sonospy-unstable\sonospy\Sonos.db, unable to open database file
Processing tags
*\* EXITING on unhandled exception - See errors/ErrorDump-20130307-181153.txt
python ./gettags.py -d Sonos.db -v \\192.168.2.38\Sonos\Sonos\ Music\12345\21\ Guns
python ./movetags.py -s Sonos.db -d Sonos.db -v

and here the ErrorDump:

<class 'sqlite3.OperationalError'>
Python 2.6: C:\python26\python.exe
Thu Mar 07 18:11:53 2013

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\sonospy-unstable\sonospy\movetags.py in <module>()
 2580 
 2581 if **name** == "**main**":
 2582     status = main()
 2583     sys.exit(status)
 2584 
status undefined
main = <function main at 0x00B6DB70>

 C:\sonospy-unstable\sonospy\movetags.py in main(argv=None)
 2575             empty_database(trackdatabase)
 2576         check_target_database_exists(trackdatabase)
 2577         process_tags(args, options, tagdatabase, trackdatabase)
 2578     filelog.close_log_files()
 2579     return 0
global process_tags = <function process_tags at 0x00B68FB0>
args = []
options = <Values at 0xb6cb20: {'the_processing': 'remove'....db', 'quiet': False, 'tagdatabase': 'Sonos.db'}>
tagdatabase = r'C:\sonospy-unstable\sonospy\Sonos.db'
trackdatabase = r'C:\sonospy-unstable\sonospy\Sonos.db'

 C:\sonospy-unstable\sonospy\movetags.py in process_tags(args=[], options=<Values at 0xb6cb20: {'the_processing': 'remove'....db', 'quiet': False, 'tagdatabase': 'Sonos.db'}>, tagdatabase=r'C:\sonospy-unstable\sonospy\Sonos.db', trackdatabase=r'C:\sonospy-unstable\sonospy\Sonos.db')
   71         cs1.execute("""create table tempdb.tags_update as select \* from tags_update""")
   72         cs1.execute("""create table tempdb.tags as select \* from tags""")
   73         cs1.execute("""create table tempdb.workvirtuals_update as select \* from workvirtuals_update""")
   74     else:
   75         db1 = sqlite3.connect(tagdatabase)
cs1 = <sqlite3.Cursor object at 0x00B69B30>
cs1.execute = <built-in method execute of sqlite3.Cursor object at 0x00B69B30>
<class 'sqlite3.OperationalError'>: no such table: workvirtuals_update
    **class** = <class 'sqlite3.OperationalError'>
    **delattr** = <method-wrapper '__delattr__' of OperationalError object at 0x00BC2B20>
    **dict** = {}
    **doc** = None
    **format** = <built-in method __format__ of OperationalError object at 0x00BC2B20>
    **getattribute** = <method-wrapper '__getattribute__' of OperationalError object at 0x00BC2B20>
    **getitem** = <method-wrapper '__getitem__' of OperationalError object at 0x00BC2B20>
    **getslice** = <method-wrapper '__getslice__' of OperationalError object at 0x00BC2B20>
    **hash** = <method-wrapper '__hash__' of OperationalError object at 0x00BC2B20>
    **init** = <method-wrapper '__init__' of OperationalError object at 0x00BC2B20>
    **module** = 'sqlite3'
    **new** = <built-in method __new__ of type object at 0x1E1D1578>
    **reduce** = <built-in method __reduce__ of OperationalError object at 0x00BC2B20>
    **reduce_ex** = <built-in method __reduce_ex__ of OperationalError object at 0x00BC2B20>
    **repr** = <method-wrapper '__repr__' of OperationalError object at 0x00BC2B20>
    **setattr** = <method-wrapper '__setattr__' of OperationalError object at 0x00BC2B20>
    **setstate** = <built-in method __setstate__ of OperationalError object at 0x00BC2B20>
    **sizeof** = <built-in method __sizeof__ of OperationalError object at 0x00BC2B20>
    **str** = <method-wrapper '__str__' of OperationalError object at 0x00BC2B20>
    **subclasshook** = <built-in method __subclasshook__ of type object at 0x00D065E0>
    **unicode** = <built-in method __unicode__ of OperationalError object at 0x00BC2B20>
    **weakref** = None
    args = ('no such table: workvirtuals_update',)
    message = 'no such table: workvirtuals_update'

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "./movetags.py", line 2582, in <module>
    status = main()
  File "./movetags.py", line 2577, in main
    process_tags(args, options, tagdatabase, trackdatabase)
  File "./movetags.py", line 73, in process_tags
    cs1.execute("""create table tempdb.workvirtuals_update as select \* from workvirtuals_update""")
OperationalError: no such table: workvirtuals_update

Any help would be much appreciated.

Thanks in advance.

Martin

**Comment by henkelis** [comment]
Hi,

The error is because there are missing tables in your database, perhaps because the scan didn't complete.

I'm a little confused as to what you're trying to do. Sonospy allows you to scan your music (creating a database of it) and then serve your music to Sonos via Sonos controllers browsing that database. Usually you would run Sonospy on a PC, with your music on a NAS - then you can access it from any Sonos controller, so an iPad for instance. To achieve that you would scan your music on the PC (using the scan.py program), and then subsequently run Sonospy on that PC.

Can you explain a little more about what you're trying to achieve please, then I can target my answers better.

Mark.

Mark.

**Comment by germangooner** [comment]
Hi Mark,

first let me thank you for your quick reply...and: sorry for the confusion.

I run Sonospy on my PC. My music is on my NAS and I scanned my music on my PC. 

I did a test-scanning with a few albums and everything was fine. I could see the files on my Ipad-Controller and play them. So I tried to scan all of my files. This didn't work out. 

I thought it might have to do with the large number of files, so I did it folder by folder. I have (because of the 65k limit) two main folders on my NAS. Each has about 60.000 files. The Subfolders are in alphabetical order from A - Z (all flac files) plus a folder for Soundtrack, Various Artists and a folder called 12345 for Bandnames starting with a number.Eventually there is one more folder named MP3,also with subfolders from A-Z etc).

I started scanning my A folder, B-folder and so on and got the first scanning problem with folder W.In cmd I got the following message after the scan: 

C:\python26\lib\cgitb.py:245: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
value = pydoc.text.repr<getattr<evalue,name>> 

So I did a reboot of my PC and got the same error. I thought it might have to do with the tags or maybe my folder structure. I had a close look at the tags and tried different folders for testing, but I have no idea where this problem comes from. So I scanned just one folder that didn't work to have the log files for help.

If you need any further information or log files: any time of course.

Thanks in advance  

Martin

**Comment by henkelis** [comment]
The DeprecationWarning message can be ignored - though it's caused by the exception handling processing trapping an error. The error displayed is explicit - there is a missing table in the database. It sounds like the database has got corrupted, which is unusual (though it can happen if the scan processing is stopped before completion. When you scanned just one folder, did you create a new database, or use the existing one?

**Comment by germangooner** [comment]
I created a new database.

**Comment by henkelis** [comment]
Can you post your command line please.

**Comment by germangooner** [comment]
Microsoft Windows XP [Version 5.1.2600](C) Copyright 1985-2001 Microsoft Corp.

C:\Dokumente und Einstellungen\admin>cd c:\sonospy-unstable\sonospy

C:\sonospy-unstable\sonospy>python scan.py -v -d Sonos.db \\192.168.2.38\Sono
s\Sonos\ Music\12345\21\ Guns >Test.log
C:\python26\lib\cgitb.py:245: DeprecationWarning: BaseException.message has been
 deprecated as of Python 2.6
  value = pydoc.text.repr(getattr(evalue, name))

C:\sonospy-unstable\sonospy>
