### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by ESikich** [henkelis/sonospy#83]
The gui tool scans for zones and then crashes:

```
Traceback (most recent call last):
  File "C:\sonospy-msrefactor5\sonospyGUI.py", line 542, in <module>
    frame = SonospyFrame()
  File "C:\sonospy-msrefactor5\sonospyGUI.py", line 105, in __init__
    notebook = SonospyNotebook(panel)
  File "C:\sonospy-msrefactor5\sonospyGUI.py", line 69, in __init__
    self.AddPage(volumeTab.VolumePanel(self), "Volume")         # 1
  File "C:\sonospy-msrefactor5\sonospy\gui\volumeTab.py", line 116, in __init__
    function = subprocess.Popen("TASKKILL /F /PID " + windowsPid[0] + " > nul", stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True)
IndexError: list index out of range
```

Running Python 2.7, Windows 10 64bit, grabbed newest sonospy zip from Github.

4 zones, name "CBBond1", "CBBond2", "JonsDesk", and "LaserArea."

Any ideas?

Edit:  Tried with Python 2.6 as well, no luck.

**Comment by chowanec** [comment]
Let me take a look and get back to you.  Can you paste the contents of you
GUIpref.ini here so I can see if it wrote anything there?

**Comment by chowanec** [comment]
Also -- please look to see if you have a windowsPID.pid file in the root of
your Sonospy folder.  I am not reproducing your issue here, so if you
could, try to rename that file and then rerun sonospyGUI.py and see if you
get the same error.  If you do, then go to the sonospy/sonospy/gui folder
and edit GUIpref.ini:

find the [volume] entry and replace zonelist = with:

zonelist = ['CBBond1']

And then at the bottom of the file add this:

[CBBond1]
max_volume = 50
quiet_volume = 35
quiet_start = 23:00
quiet_stop = 23:59
mute_start = 00:00
mute_stop = 07:00
monitor = True
monitorm = True
monitorq = True
current_volume = 50

Do these two things in that order and report back.  If deleting or renaming
windowsPID works then don't do the second step.  I vaguely remember having
a TON of problems with that file in the past.  Did you have Sonospy working
previously -- via command line or the GUI?

Thanks.

-Chow

**Comment by ESikich** [comment]
```
[virtuals]
created = 
lastmodified = 
title = <blank>
cover = <blank>
tracks = 
albumartist = <blank>
composer = <blank>
year = <blank>
genre = <blank>
discnumber = <blank>
artist = <blank>
type = -1
inserted = 

[launch]
db3_proxyname = 
db1_dbname = test.sdb
db2_check = False
db3_userindex = 0
db1_userindex = 0
db7_check = False
db1_proxyname = test
db6_proxyname = 
db4_userindex = 0
db8_check = False
db6_check = False
db6_userindex = 0
db5_proxyname = 
db2_userindex = 0
db2_dbname = <add database>
db3_dbname = <add database>
db5_userindex = 0
smapi = False
db8_dbname = <add database>
db3_check = False
db7_userindex = 0
db5_dbname = <add database>
db8_proxyname = 
db8_userindex = 0
proxy = True
db4_proxyname = 
db2_proxyname = 
db4_check = False
db1_check = True
db7_dbname = <add database>
proxyonly = True
db7_proxyname = 
db6_dbname = <add database>
db5_check = False
db4_dbname = <add database>

[scan]
folder = 
database = 
verbose = False
inioverride = 

[sonospy]
posx = 358
height = 809
width = 923
maximize = False
posy = 187

[general]
supresswarnings = False
ignoreini = pycpoint.ini scan.ini
default_music_path = 
default_sp_path = 
default_log_path = 
default_database_path = 
database_extensions = *.sdb *.db *.sqlite

[volume]
zonelist = 

[extract]
yearidx = 1
composer = 
createdval = 
modifiedidx = 1
bitrateidx = 1
bitrateval = 
overwrite = True
verbose = False
advancedquery = 
accessedval = 
createdidx = 1
genre = -1
modifiedval = 
insertedval = 
yearval = 
insertedidx = 1
last = 
database_source = 
artist = 
accessedidx = 1
database_target = 



```

GUIpref.ini

**Comment by ESikich** [comment]
Deleting the pid file first didn't do anything.

After adding to the GUIpref file, the GUI does run*, but doesn't seem to actually control anything.

Never had SonoSpy working before, this is a fresh install.

*Edit:  When I click launch I get the same error.

**Comment by chowanec** [comment]
You can check to see if it controls the volume limits on the Volume tab,
otherwise it is meant to just launch the databases for you from the command
line rather than the web interface (which does, I think, what you want).
You can also scan the databases...

Glad to know it works, will have to figure out what was causing it in the
first place.

I am travelling at the moment, so will give you instructions on how to
build your first databse, etc. when I get back home.

-Chow
